### ISSUE TITLE
String to float error with  glove.840B.300d

### ISSUE THREAD

**Issue by danielduckworth** [nirav99/WordVectorTutorial#1]
Hi, this is a great little tutorial, in particular the word triads.

I tried replacing glove.6B.50d.txt with glove.840B.300d.txt and I get the following error: 

ValueError                                Traceback (most recent call last)
<ipython-input-3-21318e4b8b23> in <module>()
      1 glove_file = "glove.840B.300d.txt"
      2 
----> 3 word, word_to_vec_map = read_glove_vectors(glove_file)
      4 print("Total words in vocabulary = " + str(len(word)))
      5 print("Size of word vectors = " + str(len(word_to_vec_map)))

<ipython-input-2-fe9c55090405> in read_glove_vectors(glove_file)
      8             curr_word = line[0]
      9             words.add(curr_word)
---> 10             word_to_vec_map[curr_word] = np.array(line[1:], dtype=np.float64)
     11 
     12     return words, word_to_vec_map

ValueError: could not convert string to float: '.'

Any ideas?

Thanks.

**Comment by nirav99** [comment]
I haven't worked with glove.840B.300d.txt, so I don't know.
